name = "geonet"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-03-04"

[build]
command = "npm run build"

[build.upload]
dir = "dist"
format = "modules"
main = "./index.mjs"

[durable_objects]
bindings = [{name = "GEONET", class_name = "Geonet"}]

[[migrations]]
tag = "v1"
new_classes = ["Geonet"]